name: CI

on:
  push:
    branches:
      - main
      - setup-ci
  pull_request:
    branches:
      - main
      - setup-ci

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js and install dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      # Install nx-cloud CLI (nếu chưa được cài)
      - run: yarn global add @nrwl/nx-cloud

      # Start Nx Cloud CI run
      - run: yarn nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - uses: nrwl/nx-set-shas@v4

      # Run affected commands
      - run: yarn nx affected -t lint test build
